AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  UrlShortnerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: url-shortner-Abhijeet
      CodeUri: hello-world/
      Handler: app.lambdaHandler
      Runtime: nodejs18.x
      MemorySize: 128
      Timeout: 10
      Environment:
        Variables:
          TABLE_NAME: url-table-Abhijeet
      Policies:
        - DynamoDBCrudPolicy:
            TableName: url-table-Abhijeet
      Events:
        ShortenUrl:
          Type: Api
          Properties:
            Path: /shorten
            Method: post
        RedirectUrl:
          Type: Api
          Properties:
            Path: /{shortUrl}
            Method: get
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
        - app.ts

  UrlTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: url-table-Abhijeet
      AttributeDefinitions:
        - AttributeName: shortUrl
          AttributeType: S
      KeySchema:
        - AttributeName: shortUrl
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
    